### ISSUE TITLE
Title not sharp

### ISSUE THREAD

**Issue by SR2k** [OskarGroth/FlatButton#10]
This may be the most stupid question but why the title text I got in the button is not as sharp as other labels. 
![Screenshot](https://user-images.githubusercontent.com/23319132/30203087-78d87c9c-94b3-11e7-954c-1fc772f06aba.jpg)

**Comment by SR2k** [comment]
Everything just work fine after I recreated a View Controller 
No idea why :-(

**Comment by gurmeherchawla** [comment]
I am facing the same issue. Upon thorough debugging, I have come to conclude that the problem arises when changing the ‘cornerRadius’ property of the ‘FlatButton’, or even of the layer of the superView.
