### ISSUE TITLE
Button image not working

### ISSUE THREAD

**Issue by grantkemp** [OskarGroth/FlatButton#13]
Hi - I am trying to add an image to a flat button - but it shows the image as being out of proportion. 
Do you know how to make the image follow the image sizes of the button?

![image](https://user-images.githubusercontent.com/751115/35276044-d15cd3bc-0039-11e8-999f-82fdcfd9451c.png)

Whereas is should look like: 

![image](https://user-images.githubusercontent.com/751115/35276053-df7a15ea-0039-11e8-987b-5ea422469605.png)

**Comment by OskarGroth** [comment]
Images must be correctly sized at the moment. Feel free to modify `setupImage()` with auto sizing and issue a pull request :)
