### ISSUE TITLE
how to change button enable in clicked

### ISSUE THREAD

**Issue by iHTCboy** [OskarGroth/FlatButton#16]
action outlet  how to setting ? plase~ thank~

**Comment by OskarGroth** [comment]
It works the same as regular `NSButton` - use a IBAction selector or just set `action` and `target` manually in code.

**Comment by iHTCboy** [comment]
@OskarGroth  thank you!  how setting button enable status?

**Comment by OskarGroth** [comment]
Still same as `NSButton`, `isEnabled`...
