### ISSUE TITLE
Objective-c version

### ISSUE THREAD

**Issue by tgsoon2002** [OskarGroth/FlatButton#17]
Hi I am new to this mac-programming.
I would like to looking for objective-c version of these project. 
What I work on, i need objective-c version. And I can't find the proper function of these code.

**Comment by OskarGroth** [comment]
Sorry, not happening. Feel free to fork and reimplement.

Also: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
