### ISSUE TITLE
Pod Install Error

### ISSUE THREAD

**Issue by kdp8791** [OskarGroth/FlatButton#4]
I am running into the following error when trying to install FlatButton using CocoaPods
```
[!] The platform of the target `Test` (iOS 10.0) is not compatible with `FlatButton (0.0.9)`, which does not support `ios`.
```

Any advice on how to resolve this error?

**Comment by OskarGroth** [comment]
FlatButton is a ```NSButton``` component for macOS.

For a similar UIKit component, see https://github.com/OskarGroth/UIButton-Bootstrap.
