### ISSUE TITLE
Swift 3.0.2 and macOS 10.12

### ISSUE THREAD

**Issue by ericdke** [OskarGroth/FlatButton#5]
Hi, the master branch uses an outdated Swift version - to fix this, I tried to manually download and use the 1.1.1 tagged .swift file but there's issues, notably the button doesn't appear until clicked, and the title is invisible. Am I doing something wrong or is this repo not ready for this yet? :) Thanks!

**Comment by OskarGroth** [comment]
I think you mean the Cocoapod was outdated. I've updated it now.
The 1.1.1 is fine. Maybe you didn't set the colors and animation correctly in IB?

**Comment by ericdke** [comment]
Oh, ok. Thanks a lot! :)
